name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package:
    uses: ./.github/workflows/setup.yml
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        run: pnpm build
