name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/setup.yml

  build-package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build package
        run: pnpm build
