name: Setup

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_path: ${{ steps.set_path.outputs.node_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer@latest | node
          echo "node_modules/.bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Set output path
        id: set_path
        run: echo "::set-output name=node_path::$(pwd)/node_modules/.bin"
