name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/setup.yml
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pnpm test
