name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/workflows/setup.yml@main  # Make sure the reference is correct

      - name: Run tests
        run: pnpm test
